version: '3.8'
services:
  api:
    restart: unless-stopped
    build:
      context: ./
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  web:
    restart: unless-stopped
    build:
      context: web
    depends_on:
      db:
        condition: service_healthy

  nginx:
    restart: unless-stopped
    image: nginx:alpine-slim
    ports:
      - "$IPADDR:$PORT:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - web

volumes:
  postgres_data:
